### ISSUE TITLE
Links at bottom of widgets broken to GHE instance

### ISSUE THREAD

**Issue by adamdmharvey** [RoadieHQ/backstage-plugin-github-insights#19] opened 2020-11-18 04:58 UTC
I use a GHE custom instance with this plugin.  I realized that all of the links at the bottom of the widgets are actually broken, all with a format of:

http://localhost:3000/mycustomgheinstance.company.com/aharvey/backstage-sample-component/graphs/contributors
http://localhost:3000/mycustomgheinstance.company.com/aharvey/backstage-sample-component/blob/master/README.md

The code which is roughly common to the various widgets to build these URLs is here:

https://github.com/RoadieHQ/backstage-plugin-github-insights/blob/1b13df113e6477e1d7bdf6fa5b3c6a73cf3fd6b1/src/components/Widgets/ContributorsCard/ContributorsCard.tsx#L56-L63

Which essentially seems to be suffixing my proper host URL and building a valid path, but defined _without the protocol_, which seems to thus be _suffixing_ all of it to my local Backstage instance (running on my laptop).

It's an interesting challenge, as in the config `integrations` key, the `apiBaseUrl` includes both protocol + host, while the `host` key contains ONLY the host.  Only the `processors` key contains a provider `target` with the full protocol + host.

For now, I guess the code quickfix could assume I'm on `https` but I suppose there could be (very !) rare edge cases where that's not the case. :)

![image](https://user-images.githubusercontent.com/33203301/99485591-b95d4a80-2930-11eb-806b-a4d93985956f.png)

**Comment by lewtakm** [comment] 2020-11-18 09:47
Hello,
I might extract full URL with a protocol from apiBaseUrl but I am not sure if it is really an issue.
Using double slashes is described here: https://tools.ietf.org/html/rfc3986#section-4.2
Double slashes notation was created for situation like this one when you don't know the URL protocol and this way you allow the browser to decide which protocol to use.

Sadly I have no experience with using GitHub Enterprise instances, can you please tell me, is it  possible to set up API URL on a different domain than GHE instance?

For example lets say that you host you GHE on ```ghe-instance.com``` and you wish to share API on ```api-ghe-instance.com``` or even a subdomain like ```api.ghe-instance.com```?

**Comment by dtuite** [comment] 2020-11-26 09:30
@adamdmharvey Hey Adam. When you say "broken", what do you mean exactly? If you click the link, what happens?

**Comment by adamdmharvey** [comment] 2020-11-27 05:08
Ah, thanks for the direct ask @dtuite.  So I took a peek and I guess my report here is more nuanced than I believed! Sorry about that.

So clicking the link does work, so apologies for confusion and now I forget if I fully tested that or not.

So the highlighted URL looks wrong in my browser status bar, but indeed if I click it, I do in fact end up on the correct pages. Both the contributor and README links take me to where I expect.

So I guess what is throwing me off, is the hover over the links which seems to suggest to me that it SHOULDN'T work.  Perhaps there is some sort of React link which JavaScript triggers which takes me to the proper place, but the highlighted A HREF is a different one and it doesn't?

I suggest it _looks_ wrong because my company's GitHub Enterprise FQDN shouldn't work off the main root `/` path of the Backstage URL, which I see in the screen shot below:

![image](https://user-images.githubusercontent.com/33203301/100413068-61b39300-3044-11eb-9031-24a179fccab4.png)

So lower priority for sure, as functionality definitely works.

**Comment by dtuite** [comment] 2020-11-27 21:58
Thanks Adam. I'm going to close this, since we believe this is a widely accepted pattern when the protocol of the URL is not known, and the linking functionality is working as intended. Thanks for confirming.

**Closed by dtuite** 2020-11-27 21:58 UTC
